spring.application.name=notification-system

spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=sumitnegi
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080